project:
  type: website
  output-dir: _site
  render:
    - '*.qmd'


website:
  title: "Data Analytics Careers in Financial Services"
  navbar:
    left:
      - href: index.qmd
      - href: introduction.qmd
        text: "Project Overview"
      - href: market_baseline.qmd
        text: "Market Baseline"
      - href: career_evaluation.qmd
        text: "Career Evaluation"


sidebar:
    style: docked
    contents:
      - href: index.qmd
      - href: introduction.qmd
        text: "Project Overview"
      - href: old_data_preparation.qmd #Old one
        text: "(old)Data Preparation"    # Old one
      - href: data_preparation.qmd
        text: "Data Preparation"
      - href: skill_gap_analysis.qmd
        text: "Skill Gap Analysis"
      - href: ml_methods.qmd
        text: "Predictive Modeling"
      - href: final_recommendations.qmd
        text: "Recommendations"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  echo: true
  eval: true

  code-fold: true
  bibliography: references.bib
