<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data Analyst Careers in Financial Services – Data Analytics Careers in Financial Services</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-d779191fb58665fba6013d76b5d4c7b3.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Data Analytics Careers in Financial Services</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./introduction.html" aria-current="page"> 
<span class="menu-text">Project Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./market_baseline.html"> 
<span class="menu-text">Market Baseline</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./final_recommendations.html"> 
<span class="menu-text">Recommendations</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./final_report.html"> 
<span class="menu-text">Final Report</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./final_report.html">Final Report</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Product Framing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_preparation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Scope and Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./market_baseline.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Market Baseline</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./skill_gap_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Skill-Gap Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ml_methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Final Analytics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./final_recommendations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Recommendations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./limitations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. Limitations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./final_report.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Final Report</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#sec-product-framing" id="toc-sec-product-framing" class="nav-link active" data-scroll-target="#sec-product-framing"><span class="header-section-number">1</span> Product Framing</a>
  <ul class="collapse">
  <li><a href="#research-rationale" id="toc-research-rationale" class="nav-link" data-scroll-target="#research-rationale"><span class="header-section-number">1.1</span> Research rationale</a></li>
  <li><a href="#scope-and-research-questions" id="toc-scope-and-research-questions" class="nav-link" data-scroll-target="#scope-and-research-questions"><span class="header-section-number">1.2</span> Scope and research questions</a>
  <ul class="collapse">
  <li><a href="#industry-and-career-scope-selection" id="toc-industry-and-career-scope-selection" class="nav-link" data-scroll-target="#industry-and-career-scope-selection"><span class="header-section-number">1.2.1</span> Industry and career scope selection</a></li>
  <li><a href="#primary-project-question" id="toc-primary-project-question" class="nav-link" data-scroll-target="#primary-project-question"><span class="header-section-number">1.2.2</span> Primary project question</a></li>
  <li><a href="#job-seeker-decisions" id="toc-job-seeker-decisions" class="nav-link" data-scroll-target="#job-seeker-decisions"><span class="header-section-number">1.2.3</span> Job-seeker decisions</a></li>
  </ul></li>
  <li><a href="#short-literature-review" id="toc-short-literature-review" class="nav-link" data-scroll-target="#short-literature-review"><span class="header-section-number">1.3</span> Short literature review</a></li>
  <li><a href="#data-fields-and-intended-use" id="toc-data-fields-and-intended-use" class="nav-link" data-scroll-target="#data-fields-and-intended-use"><span class="header-section-number">1.4</span> Data fields and intended use</a></li>
  <li><a href="#study-and-product-limitations" id="toc-study-and-product-limitations" class="nav-link" data-scroll-target="#study-and-product-limitations"><span class="header-section-number">1.5</span> Study and Product Limitations</a></li>
  </ul></li>
  <li><a href="#sec-scope-data" id="toc-sec-scope-data" class="nav-link" data-scroll-target="#sec-scope-data"><span class="header-section-number">2</span> Scope and Data</a>
  <ul class="collapse">
  <li><a href="#step-2-objective" id="toc-step-2-objective" class="nav-link" data-scroll-target="#step-2-objective"><span class="header-section-number">2.1</span> Step 2 Objective</a></li>
  <li><a href="#data-source" id="toc-data-source" class="nav-link" data-scroll-target="#data-source"><span class="header-section-number">2.2</span> Data Source</a></li>
  <li><a href="#industry-filter" id="toc-industry-filter" class="nav-link" data-scroll-target="#industry-filter"><span class="header-section-number">2.3</span> Industry Filter</a></li>
  <li><a href="#career-filter" id="toc-career-filter" class="nav-link" data-scroll-target="#career-filter"><span class="header-section-number">2.4</span> Career Filter</a></li>
  <li><a href="#cleaning-decisions" id="toc-cleaning-decisions" class="nav-link" data-scroll-target="#cleaning-decisions"><span class="header-section-number">2.5</span> Cleaning Decisions</a>
  <ul class="collapse">
  <li><a href="#duplicate-records" id="toc-duplicate-records" class="nav-link" data-scroll-target="#duplicate-records"><span class="header-section-number">2.5.1</span> Duplicate Records</a></li>
  <li><a href="#salary" id="toc-salary" class="nav-link" data-scroll-target="#salary"><span class="header-section-number">2.5.2</span> Salary</a></li>
  <li><a href="#experience" id="toc-experience" class="nav-link" data-scroll-target="#experience"><span class="header-section-number">2.5.3</span> Experience</a></li>
  <li><a href="#remote-work" id="toc-remote-work" class="nav-link" data-scroll-target="#remote-work"><span class="header-section-number">2.5.4</span> Remote Work</a></li>
  <li><a href="#location" id="toc-location" class="nav-link" data-scroll-target="#location"><span class="header-section-number">2.5.5</span> Location</a></li>
  <li><a href="#education-and-skills" id="toc-education-and-skills" class="nav-link" data-scroll-target="#education-and-skills"><span class="header-section-number">2.5.6</span> Education and Skills</a></li>
  </ul></li>
  <li><a href="#final-analytical-dataset" id="toc-final-analytical-dataset" class="nav-link" data-scroll-target="#final-analytical-dataset"><span class="header-section-number">2.6</span> Final Analytical Dataset</a></li>
  <li><a href="#step-2-limitations" id="toc-step-2-limitations" class="nav-link" data-scroll-target="#step-2-limitations"><span class="header-section-number">2.7</span> Step 2 Limitations</a></li>
  </ul></li>
  <li><a href="#sec-market-baseline" id="toc-sec-market-baseline" class="nav-link" data-scroll-target="#sec-market-baseline"><span class="header-section-number">3</span> Market Baseline</a>
  <ul class="collapse">
  <li><a href="#market-baseline" id="toc-market-baseline" class="nav-link" data-scroll-target="#market-baseline"><span class="header-section-number">3.1</span> Market Baseline</a></li>
  <li><a href="#industry-scope" id="toc-industry-scope" class="nav-link" data-scroll-target="#industry-scope"><span class="header-section-number">3.2</span> Industry Scope</a></li>
  <li><a href="#job-volume-by-title" id="toc-job-volume-by-title" class="nav-link" data-scroll-target="#job-volume-by-title"><span class="header-section-number">3.3</span> Job Volume by Title</a></li>
  <li><a href="#top-employers" id="toc-top-employers" class="nav-link" data-scroll-target="#top-employers"><span class="header-section-number">3.4</span> Top Employers</a></li>
  <li><a href="#hiring-locations" id="toc-hiring-locations" class="nav-link" data-scroll-target="#hiring-locations"><span class="header-section-number">3.5</span> Hiring Locations</a></li>
  <li><a href="#remote-work-1" id="toc-remote-work-1" class="nav-link" data-scroll-target="#remote-work-1"><span class="header-section-number">3.6</span> Remote Work</a></li>
  <li><a href="#salary-distribution" id="toc-salary-distribution" class="nav-link" data-scroll-target="#salary-distribution"><span class="header-section-number">3.7</span> Salary Distribution</a></li>
  <li><a href="#experience-requirements" id="toc-experience-requirements" class="nav-link" data-scroll-target="#experience-requirements"><span class="header-section-number">3.8</span> Experience Requirements</a></li>
  <li><a href="#data-quality-and-limitations" id="toc-data-quality-and-limitations" class="nav-link" data-scroll-target="#data-quality-and-limitations"><span class="header-section-number">3.9</span> Data Quality and Limitations</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">3.10</span> Summary</a></li>
  </ul></li>
  <li><a href="#sec-skill-gap" id="toc-sec-skill-gap" class="nav-link" data-scroll-target="#sec-skill-gap"><span class="header-section-number">4</span> Skill-Gap Analysis</a>
  <ul class="collapse">
  <li><a href="#skill-gap-analysis" id="toc-skill-gap-analysis" class="nav-link" data-scroll-target="#skill-gap-analysis"><span class="header-section-number">4.1</span> Skill Gap Analysis</a></li>
  <li><a href="#team-skill-self-assessment" id="toc-team-skill-self-assessment" class="nav-link" data-scroll-target="#team-skill-self-assessment"><span class="header-section-number">4.2</span> Team Skill Self-Assessment</a></li>
  <li><a href="#market-skill-demand" id="toc-market-skill-demand" class="nav-link" data-scroll-target="#market-skill-demand"><span class="header-section-number">4.3</span> Market Skill Demand</a></li>
  <li><a href="#skill-priority-matrix" id="toc-skill-priority-matrix" class="nav-link" data-scroll-target="#skill-priority-matrix"><span class="header-section-number">4.4</span> Skill Priority Matrix</a></li>
  <li><a href="#key-skill-gaps" id="toc-key-skill-gaps" class="nav-link" data-scroll-target="#key-skill-gaps"><span class="header-section-number">4.5</span> Key Skill Gaps</a></li>
  <li><a href="#team-strengths" id="toc-team-strengths" class="nav-link" data-scroll-target="#team-strengths"><span class="header-section-number">4.6</span> Team Strengths</a></li>
  <li><a href="#individual-development-priorities" id="toc-individual-development-priorities" class="nav-link" data-scroll-target="#individual-development-priorities"><span class="header-section-number">4.7</span> Individual Development Priorities</a>
  <ul class="collapse">
  <li><a href="#taiqi" id="toc-taiqi" class="nav-link" data-scroll-target="#taiqi"><span class="header-section-number">4.7.1</span> Taiqi</a></li>
  <li><a href="#joseph" id="toc-joseph" class="nav-link" data-scroll-target="#joseph"><span class="header-section-number">4.7.2</span> Joseph</a></li>
  <li><a href="#igor" id="toc-igor" class="nav-link" data-scroll-target="#igor"><span class="header-section-number">4.7.3</span> Igor</a></li>
  </ul></li>
  <li><a href="#improvement-plan" id="toc-improvement-plan" class="nav-link" data-scroll-target="#improvement-plan"><span class="header-section-number">4.8</span> Improvement Plan</a></li>
  <li><a href="#team-collaboration" id="toc-team-collaboration" class="nav-link" data-scroll-target="#team-collaboration"><span class="header-section-number">4.9</span> Team Collaboration</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">4.10</span> Limitations</a></li>
  <li><a href="#summary-1" id="toc-summary-1" class="nav-link" data-scroll-target="#summary-1"><span class="header-section-number">4.11</span> Summary</a></li>
  </ul></li>
  <li><a href="#sec-final-analytics" id="toc-sec-final-analytics" class="nav-link" data-scroll-target="#sec-final-analytics"><span class="header-section-number">5</span> Final Analytics</a>
  <ul class="collapse">
  <li><a href="#purpose" id="toc-purpose" class="nav-link" data-scroll-target="#purpose"><span class="header-section-number">5.1</span> Purpose</a></li>
  <li><a href="#data-used" id="toc-data-used" class="nav-link" data-scroll-target="#data-used"><span class="header-section-number">5.2</span> Data Used</a></li>
  <li><a href="#how-the-models-were-checked" id="toc-how-the-models-were-checked" class="nav-link" data-scroll-target="#how-the-models-were-checked"><span class="header-section-number">5.3</span> How the Models Were Checked</a></li>
  <li><a href="#main-results" id="toc-main-results" class="nav-link" data-scroll-target="#main-results"><span class="header-section-number">5.4</span> Main Results</a></li>
  <li><a href="#which-factor-contributed-most" id="toc-which-factor-contributed-most" class="nav-link" data-scroll-target="#which-factor-contributed-most"><span class="header-section-number">5.5</span> Which Factor Contributed Most?</a></li>
  <li><a href="#what-this-means-for-a-job-seeker" id="toc-what-this-means-for-a-job-seeker" class="nav-link" data-scroll-target="#what-this-means-for-a-job-seeker"><span class="header-section-number">5.6</span> What This Means for a Job Seeker</a></li>
  <li><a href="#limitations-1" id="toc-limitations-1" class="nav-link" data-scroll-target="#limitations-1"><span class="header-section-number">5.7</span> Limitations</a></li>
  </ul></li>
  <li><a href="#sec-recommendations" id="toc-sec-recommendations" class="nav-link" data-scroll-target="#sec-recommendations"><span class="header-section-number">6</span> Recommendations</a>
  <ul class="collapse">
  <li><a href="#where-to-focus" id="toc-where-to-focus" class="nav-link" data-scroll-target="#where-to-focus"><span class="header-section-number">6.1</span> Where to Focus</a></li>
  <li><a href="#build-the-skills-employers-request" id="toc-build-the-skills-employers-request" class="nav-link" data-scroll-target="#build-the-skills-employers-request"><span class="header-section-number">6.2</span> 1. Build the Skills Employers Request</a></li>
  <li><a href="#target-roles-that-fit-your-experience" id="toc-target-roles-that-fit-your-experience" class="nav-link" data-scroll-target="#target-roles-that-fit-your-experience"><span class="header-section-number">6.3</span> 2. Target Roles That Fit Your Experience</a></li>
  <li><a href="#use-salary-as-a-benchmark" id="toc-use-salary-as-a-benchmark" class="nav-link" data-scroll-target="#use-salary-as-a-benchmark"><span class="header-section-number">6.4</span> 3. Use Salary as a Benchmark</a></li>
  <li><a href="#search-across-employers-and-work-arrangements" id="toc-search-across-employers-and-work-arrangements" class="nav-link" data-scroll-target="#search-across-employers-and-work-arrangements"><span class="header-section-number">6.5</span> 4. Search Across Employers and Work Arrangements</a></li>
  <li><a href="#a-practical-next-step" id="toc-a-practical-next-step" class="nav-link" data-scroll-target="#a-practical-next-step"><span class="header-section-number">6.6</span> A Practical Next Step</a></li>
  <li><a href="#limitations-of-these-recommendations" id="toc-limitations-of-these-recommendations" class="nav-link" data-scroll-target="#limitations-of-these-recommendations"><span class="header-section-number">6.7</span> Limitations of These Recommendations</a></li>
  </ul></li>
  <li><a href="#sec-limitations" id="toc-sec-limitations" class="nav-link" data-scroll-target="#sec-limitations"><span class="header-section-number">7</span> Limitations</a>
  <ul class="collapse">
  <li><a href="#limits-of-the-evidence" id="toc-limits-of-the-evidence" class="nav-link" data-scroll-target="#limits-of-the-evidence"><span class="header-section-number">7.1</span> Limits of the Evidence</a></li>
  <li><a href="#product-boundaries-and-next-steps" id="toc-product-boundaries-and-next-steps" class="nav-link" data-scroll-target="#product-boundaries-and-next-steps"><span class="header-section-number">7.2</span> Product Boundaries and Next Steps</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="final_report.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Data Analyst Careers in Financial Services</h1>
<p class="subtitle lead">Group 4 | BU MET AD688 | Career readiness in NAICS 523</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="sec-product-framing" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Product Framing</h1>
<section id="research-rationale" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="research-rationale"><span class="header-section-number">1.1</span> Research rationale</h2>
<p>Students preparing for Data Analyst careers must connect their current capabilities to the requirements of actual employers. A job title alone does not explain which skills a position requires, how much experience is expected, whether compensation is disclosed, or whether the work arrangement fits a job seeker’s circumstances. This project develops a career evaluation prototype for students and aspiring Data Analysts considering securities, investments, and related financial activities.</p>
<p>The target user is a student or early-career job seeker pursuing a <strong>Data Analyst / Data Analytics</strong> pathway. The primary focus is <strong>skill and career readiness</strong>. Salary, experience, location, and employment patterns provide supporting evidence for deciding where to apply and what to learn next. This framing follows the AD688 running case, which asks teams to connect an industry-scoped dataset to practical job-seeker decisions.</p>
<p>Reliable industry labels are important because an incorrectly classified employer can distort a sector-specific career benchmark. Chern et al.&nbsp;investigate employer-industry errors arising from employer identification and industry attributes, using posting-derived signals to help detect them <span class="citation" data-cites="chern2018">(<a href="#ref-chern2018" role="doc-biblioref">Chern et al. 2018</a>)</span>. For this project, the implication is to document how industry membership is selected and to treat potentially inconsistent employer labels as a data-quality limitation.</p>
<p>The completed study uses <strong>140 Lightcast postings from May–September 2024</strong>, representing <strong>102 distinct employer/title/description profiles</strong>. It moves from data preparation and the market baseline to skill gaps, salary analysis and practical career recommendations. Salary is available for <strong>86 postings</strong>, representing <strong>48 distinct profiles</strong>; the remaining postings still inform the wider market and skill analysis.</p>
</section>
<section id="scope-and-research-questions" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="scope-and-research-questions"><span class="header-section-number">1.2</span> Scope and research questions</h2>
<section id="industry-and-career-scope-selection" class="level3" data-number="1.2.1">
<h3 data-number="1.2.1" class="anchored" data-anchor-id="industry-and-career-scope-selection"><span class="header-section-number">1.2.1</span> Industry and career scope selection</h3>
<p><strong>Financial Services – Data Analytics</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 75%">
</colgroup>
<thead>
<tr class="header">
<th>Scope component</th>
<th>Selected scope</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Target career pathway</td>
<td>Data Analyst / Data Analytics</td>
</tr>
<tr class="even">
<td>NAICS classification revision</td>
<td>2022</td>
</tr>
<tr class="odd">
<td>Selected dataset code</td>
<td><code>523</code></td>
</tr>
<tr class="even">
<td>Industry label</td>
<td>Securities, Commodity Contracts, and Other Financial Investments and Related Activities</td>
</tr>
<tr class="odd">
<td>Primary analytical focus</td>
<td>Skill and career readiness</td>
</tr>
<tr class="even">
<td>Supporting dimensions</td>
<td>Salary, experience, geography, remote work, and employers</td>
</tr>
</tbody>
</table>
<p>NAICS 523 covers securities and commodity intermediation, exchanges, and other investment-related services. It is narrower than the full Finance and Insurance sector and does not represent all financial-services employment. NAICS describes the economic activity of an establishment; it does not identify an employee’s occupation <span class="citation" data-cites="naics2022">(<a href="#ref-naics2022" role="doc-biblioref">Executive Office of the President, Office of Management and Budget 2022</a>)</span>. A Data Analyst title and an employer’s industry code therefore serve different purposes in the cohort definition.</p>
<p>Group 4 uses the three-digit subsector to examine Data Analyst opportunities across related investment activities. The findings apply to this selected cohort, rather than all financial-services employment. A separate career-title filter identifies the Data Analyst roles within the industry.</p>
<p>Reference: <a href="https://www.naics.com/naics-code-description/?code=523">NAICS 523 industry description</a>.</p>
</section>
<section id="primary-project-question" class="level3" data-number="1.2.2">
<h3 data-number="1.2.2" class="anchored" data-anchor-id="primary-project-question"><span class="header-section-number">1.2.2</span> Primary project question</h3>
<blockquote class="blockquote">
<p>What skills, experience levels, salary opportunities, and employment patterns should aspiring Data Analysts understand when pursuing careers in securities, investments, and related financial services (NAICS 523), and how can job seekers use these factors to evaluate their career readiness and identify areas for upskilling?</p>
</blockquote>
</section>
<section id="job-seeker-decisions" class="level3" data-number="1.2.3">
<h3 data-number="1.2.3" class="anchored" data-anchor-id="job-seeker-decisions"><span class="header-section-number">1.2.3</span> Job-seeker decisions</h3>
<ul>
<li><strong>Skills:</strong> Which tools should I strengthen and demonstrate in a portfolio?</li>
<li><strong>Experience:</strong> Which roles match my background and stated requirements?</li>
<li><strong>Compensation:</strong> What salary benchmark can help me compare similar roles?</li>
<li><strong>Search priorities:</strong> Which employers, locations and work arrangements should I investigate?</li>
</ul>
</section>
</section>
<section id="short-literature-review" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="short-literature-review"><span class="header-section-number">1.3</span> Short literature review</h2>
<p>Five sources support the project’s scope, data-quality approach, and interpretation. This is a focused narrative review rather than a systematic review.</p>
<p><strong>Employer-industry classification.</strong> Goindani et al.&nbsp;examine employer-industry classification using job postings <span class="citation" data-cites="goindani2017">(<a href="#ref-goindani2017" role="doc-biblioref">Goindani et al. 2017</a>)</span>. The study provides a methodological reference for using recruitment records to examine employer classification. Its relevance here is to make industry selection explicit and review questionable labels. Classification research provides context for cohort quality; it does not establish skill demand or salary levels in this project’s NAICS 523 sample.</p>
<p><strong>Industry-label error detection.</strong> Chern et al.&nbsp;use employer names, employer descriptions, job titles, and job descriptions to identify possible industry-classification errors, comparing support vector machine and random forest approaches <span class="citation" data-cites="chern2018">(<a href="#ref-chern2018" role="doc-biblioref">Chern et al. 2018</a>)</span>. Their findings motivate checking employer and posting information when industry membership is uncertain. The paper’s predictive results concern its own dataset and are not evidence of this project’s accuracy or a requirement to reproduce its models.</p>
<p><strong>Representativeness of online postings.</strong> Tsvetkova et al.&nbsp;compare Lightcast vacancies with official sources in Australia, Canada, the United Kingdom, and the United States <span class="citation" data-cites="tsvetkova2024">(<a href="#ref-tsvetkova2024" role="doc-biblioref">Tsvetkova et al. 2024</a>)</span>. They identify variation in representativeness across geography, occupation, and industry. This supports reporting the observed posting sample and its coverage rather than equating posting counts with all vacancies or employment. Their results do not provide a correction factor for the MET Career Compass dataset.</p>
<p><strong>Industry definition and analytical boundaries.</strong> The 2022 NAICS manual supplies the classification framework used to define the selected subsector <span class="citation" data-cites="naics2022">(<a href="#ref-naics2022" role="doc-biblioref">Executive Office of the President, Office of Management and Budget 2022</a>)</span>. It supports keeping employer industry distinct from career pathway and retaining detailed industry labels for interpretation. This prevents a financial-services label from being used as a substitute for a Data Analyst title filter.</p>
<p><strong>Reproducible analytical implementation.</strong> Pedregosa et al.&nbsp;describe scikit-learn as a general-purpose Python machine-learning library <span class="citation" data-cites="pedregosa2011">(<a href="#ref-pedregosa2011" role="doc-biblioref">Pedregosa et al. 2011</a>)</span>. The project uses Python to compare multiple linear regression, Random Forest and an average-salary baseline. The analysis notebook documents preprocessing and checks predictions on held-out posting groups, keeping repeated job descriptions together. The software paper does not establish which skills financial employers require or validate a career-readiness scorecard.</p>
<p>Together, these sources support an industry-scoped, reproducible career benchmark with explicit limits. The project’s contribution is to turn posting evidence and self-assessed skills into interpretable learning and application priorities. The recommendations prioritize SQL, Python and BI development, matching experience requirements, using descriptive salary benchmarks and verifying work arrangements. The salary models provide supporting evidence; they do not define a job seeker’s readiness. The project does not claim to improve a proprietary classification system or demonstrate that acquiring a particular skill causes employment.</p>
</section>
<section id="data-fields-and-intended-use" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="data-fields-and-intended-use"><span class="header-section-number">1.4</span> Data fields and intended use</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 74%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>ID</code></td>
<td>Unique Lightcast job-posting identifier.</td>
</tr>
<tr class="even">
<td><code>LAST_UPDATED_DATE</code></td>
<td>Date the job posting record was last updated.</td>
</tr>
<tr class="odd">
<td><code>POSTED</code></td>
<td>Date the job posting was posted.</td>
</tr>
<tr class="even">
<td><code>EXPIRED</code></td>
<td>Date the job posting expired, when available.</td>
</tr>
<tr class="odd">
<td><code>TITLE_RAW</code></td>
<td>Original job title from the Lightcast posting.</td>
</tr>
<tr class="even">
<td><code>BODY</code></td>
<td>Job-posting description text.</td>
</tr>
<tr class="odd">
<td><code>COMPANY_NAME</code></td>
<td>Employer name.</td>
</tr>
<tr class="even">
<td><code>EDUCATION_LEVELS_NAME</code></td>
<td>Education-level information associated with the posting.</td>
</tr>
<tr class="odd">
<td><code>MIN_YEARS_EXPERIENCE</code></td>
<td>Minimum years of experience required, when available.</td>
</tr>
<tr class="even">
<td><code>MAX_YEARS_EXPERIENCE</code></td>
<td>Maximum years of experience required, when available.</td>
</tr>
<tr class="odd">
<td><code>SALARY</code></td>
<td>Original salary field.</td>
</tr>
<tr class="even">
<td><code>REMOTE_TYPE</code></td>
<td>Lightcast remote-work classification code.</td>
</tr>
<tr class="odd">
<td><code>REMOTE_TYPE_NAME</code></td>
<td>Readable remote-work classification.</td>
</tr>
<tr class="even">
<td><code>ORIGINAL_PAY_PERIOD</code></td>
<td>Original pay-period label; stored salary amounts are already annualized.</td>
</tr>
<tr class="odd">
<td><code>SALARY_TO</code></td>
<td>Upper annualized salary endpoint used in the analysis.</td>
</tr>
<tr class="even">
<td><code>SALARY_FROM</code></td>
<td>Lower annualized salary endpoint used in the analysis.</td>
</tr>
<tr class="odd">
<td><code>LOCATION</code></td>
<td>Original job location field.</td>
</tr>
<tr class="even">
<td><code>CITY_NAME</code></td>
<td>City associated with the posting.</td>
</tr>
<tr class="odd">
<td><code>STATE_NAME</code></td>
<td>State associated with the posting.</td>
</tr>
<tr class="even">
<td><code>NAICS3</code></td>
<td>Three-digit NAICS industry subsector code.</td>
</tr>
<tr class="odd">
<td><code>NAICS3_NAME</code></td>
<td>Name of the three-digit NAICS industry subsector.</td>
</tr>
<tr class="even">
<td><code>TITLE</code></td>
<td>Standardized Lightcast job title.</td>
</tr>
<tr class="odd">
<td><code>TITLE_NAME</code></td>
<td>Named occupational/job-title classification.</td>
</tr>
<tr class="even">
<td><code>TITLE_CLEAN</code></td>
<td>Cleaned job title field.</td>
</tr>
<tr class="odd">
<td><code>SKILLS</code></td>
<td>Lightcast coded skills associated with the posting.</td>
</tr>
<tr class="even">
<td><code>SKILLS_NAME</code></td>
<td>Readable skill names.</td>
</tr>
<tr class="odd">
<td><code>SPECIALIZED_SKILLS</code></td>
<td>Lightcast specialized skill codes.</td>
</tr>
<tr class="even">
<td><code>SPECIALIZED_SKILLS_NAME</code></td>
<td>Readable specialized skill names.</td>
</tr>
<tr class="odd">
<td><code>COMMON_SKILLS</code></td>
<td>Lightcast common skill codes.</td>
</tr>
<tr class="even">
<td><code>COMMON_SKILLS_NAME</code></td>
<td>Readable common skill names.</td>
</tr>
<tr class="odd">
<td><code>SOFTWARE_SKILLS</code></td>
<td>Lightcast software skill codes.</td>
</tr>
<tr class="even">
<td><code>SOFTWARE_SKILLS_NAME</code></td>
<td>Readable software skill names.</td>
</tr>
<tr class="odd">
<td><code>ONET</code></td>
<td>O*NET occupation code.</td>
</tr>
<tr class="even">
<td><code>ONET_NAME</code></td>
<td>O*NET occupation name.</td>
</tr>
<tr class="odd">
<td><code>SOC_2021_5</code></td>
<td>Five-digit SOC 2021 occupation code.</td>
</tr>
<tr class="even">
<td><code>SOC_2021_5_NAME</code></td>
<td>Name of the five-digit SOC 2021 occupation classification.</td>
</tr>
<tr class="odd">
<td><code>remote_status</code></td>
<td>Cleaned remote-work classification; missing classifications are labeled Unknown.</td>
</tr>
<tr class="even">
<td><code>city_clean</code></td>
<td>Cleaned city field.</td>
</tr>
<tr class="odd">
<td><code>state_clean</code></td>
<td>Cleaned state field.</td>
</tr>
<tr class="even">
<td><code>salary_midpoint</code></td>
<td>Average of the two annualized salary endpoints; target of the salary regression.</td>
</tr>
<tr class="odd">
<td><code>industry_scope</code></td>
<td>Analysis industry scope, defined as NAICS 523.</td>
</tr>
<tr class="even">
<td><code>career_scope</code></td>
<td>Career filter used for the revised core Data Analyst sample.</td>
</tr>
</tbody>
</table>
</section>
<section id="study-and-product-limitations" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="study-and-product-limitations"><span class="header-section-number">1.5</span> Study and Product Limitations</h2>
<p>The findings are exploratory because the sample is small, historical and unevenly distributed across regions and employers. Salary disclosure and missing job requirements further limit generalization. The career-readiness prototype helps organize learning and compare roles; it does not yet verify readiness or predict individual offers reliably. The report’s <a href="./limitations.html">Limitations</a> section documents these boundaries and the next improvements.</p>
</section>
</section>
<section id="sec-scope-data" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Scope and Data</h1>
<section id="step-2-objective" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="step-2-objective"><span class="header-section-number">2.1</span> Step 2 Objective</h2>
<p>This step prepares the career-market data used to evaluate opportunities for Data Analyst careers within the selected financial-services industry.</p>
<p>The analysis is anchored to:</p>
<ul>
<li><strong>Career pathway:</strong> Data Analyst / Data Analytics</li>
<li><strong>NAICS:</strong> 523</li>
<li><strong>Industry:</strong> Securities, Commodity Contracts, and Other Financial Investments and Related Activities</li>
</ul>
<p>The objective is to create a cleaned, reproducible dataset that can be used to evaluate job availability, compensation, experience requirements, work arrangements, geography, employers, and skills.</p>
</section>
<section id="data-source" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="data-source"><span class="header-section-number">2.2</span> Data Source</h2>
<p>The analysis uses the professor-approved Lightcast job-postings dataset provided through the team’s Google Drive dataset.</p>
<p>The dataset contains job-posting information including job titles, employers, locations, salary information, experience requirements, education, remote-work classifications, skills, occupation classifications, and NAICS industry classifications.</p>
</section>
<section id="industry-filter" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="industry-filter"><span class="header-section-number">2.3</span> Industry Filter</h2>
<p>The analysis is restricted to <strong>NAICS 523</strong>, the three-digit NAICS subsector:</p>
<blockquote class="blockquote">
<p>Securities, Commodity Contracts, and Other Financial Investments and Related Activities</p>
</blockquote>
<p>The Lightcast dataset contains <strong>942 job postings</strong> classified under NAICS 523.</p>
<p>Using the three-digit <code>NAICS3</code> field ensures that the analysis covers the full selected NAICS subsector rather than treating <code>523000</code> as a separate six-digit industry code.</p>
</section>
<section id="career-filter" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="career-filter"><span class="header-section-number">2.4</span> Career Filter</h2>
<p>The career pathway is <strong>Data Analyst / Data Analytics</strong>.</p>
<p>A title-based filter was used to identify postings containing Data Analyst terminology. Clearly unrelated specialized categories were excluded when the title indicated a maintenance, cybersecurity, academic, internship, platform-services, CV-22, or SC2 role.</p>
<p>The resulting core career-market dataset contains <strong>140 postings</strong>.</p>
<p>This core dataset is used as the baseline for Step 2. Closely related analytics roles may be incorporated into the broader Step 3 skill-gap analysis where appropriate.</p>
</section>
<section id="cleaning-decisions" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="cleaning-decisions"><span class="header-section-number">2.5</span> Cleaning Decisions</h2>
<section id="duplicate-records" class="level3" data-number="2.5.1">
<h3 data-number="2.5.1" class="anchored" data-anchor-id="duplicate-records"><span class="header-section-number">2.5.1</span> Duplicate Records</h3>
<p>Postings were checked using the Lightcast <code>ID</code> field. No duplicate IDs were removed from the 140-posting analytical dataset.</p>
</section>
<section id="salary" class="level3" data-number="2.5.2">
<h3 data-number="2.5.2" class="anchored" data-anchor-id="salary"><span class="header-section-number">2.5.2</span> Salary</h3>
<p>Salary fields were converted to numeric values where possible. Hourly and monthly amounts were annualized during the earlier preparation, so the stored endpoints are used without another conversion. The original pay-period label can remain unchanged.</p>
<p>Missing salary values were retained as missing rather than converted to zero.</p>
<p>A salary midpoint was calculated when both the lower and upper salary values were available:</p>
<p><span class="math display">\[
Salary\ Midpoint =
\frac{Salary\ From + Salary\ To}{2}
\]</span></p>
<p>There were <strong>86 postings with a usable salary midpoint</strong>.</p>
<p>Across the 86 posting rows, the observed annual salary midpoint ranged from <strong>$24,960 to $160,000</strong>, with a median of <strong>$93,850</strong>. After counting repeated employer/title/description profiles once, the median across 48 salary profiles is approximately <strong>$92,300</strong>.</p>
<p>Because salary information is not available for every posting, these figures describe the subset of postings reporting usable salary ranges.</p>
</section>
<section id="experience" class="level3" data-number="2.5.3">
<h3 data-number="2.5.3" class="anchored" data-anchor-id="experience"><span class="header-section-number">2.5.3</span> Experience</h3>
<p>Minimum and maximum experience requirements were retained separately.</p>
<p>Negative or invalid experience values were treated as missing.</p>
<p>A minimum experience requirement was available for <strong>112 of the 140 postings</strong>.</p>
<p>Among postings with reported minimum experience, the median requirement was <strong>5 years</strong>, with an average of approximately <strong>4.1 years</strong>.</p>
<p>Maximum experience was substantially less complete and was therefore not imputed.</p>
</section>
<section id="remote-work" class="level3" data-number="2.5.4">
<h3 data-number="2.5.4" class="anchored" data-anchor-id="remote-work"><span class="header-section-number">2.5.4</span> Remote Work</h3>
<p>Remote-work classifications were retained from the Lightcast data.</p>
<p>The cleaned categories are:</p>
<ul>
<li>Remote</li>
<li>Hybrid Remote</li>
<li>Not Remote</li>
<li>Unknown</li>
</ul>
<p>Of the 140 postings:</p>
<ul>
<li><strong>54</strong> were classified as Remote</li>
<li><strong>12</strong> were classified as Hybrid Remote</li>
<li><strong>3</strong> were classified as Not Remote</li>
<li><strong>71</strong> had an unknown classification</li>
</ul>
<p>Unknown values were retained because an unavailable classification does not necessarily mean that the position is onsite.</p>
</section>
<section id="location" class="level3" data-number="2.5.5">
<h3 data-number="2.5.5" class="anchored" data-anchor-id="location"><span class="header-section-number">2.5.5</span> Location</h3>
<p>City and state information were retained for geographic analysis.</p>
<p>No postings were missing the cleaned city or state fields in the analytical dataset.</p>
<p>The location data were used to identify the leading hiring states and locations represented in the sample.</p>
</section>
<section id="education-and-skills" class="level3" data-number="2.5.6">
<h3 data-number="2.5.6" class="anchored" data-anchor-id="education-and-skills"><span class="header-section-number">2.5.6</span> Education and Skills</h3>
<p>Education and skill fields were retained from the Lightcast dataset.</p>
<p>Missing values were not converted into assumptions about required education or skills.</p>
<p>These fields provide the foundation for the later skill-gap analysis.</p>
</section>
</section>
<section id="final-analytical-dataset" class="level2" data-number="2.6">
<h2 data-number="2.6" class="anchored" data-anchor-id="final-analytical-dataset"><span class="header-section-number">2.6</span> Final Analytical Dataset</h2>
<p>The cleaned Step 2 dataset contains:</p>
<ul>
<li><strong>140 job postings</strong></li>
<li><strong>52 employers</strong></li>
<li><strong>62 distinct job titles</strong></li>
<li><strong>36 original analytical variables</strong></li>
<li>Additional cleaned variables for remote status, location, salary midpoint, industry scope, and career scope</li>
</ul>
<p>The cleaned dataset is stored as:</p>
<p><code>data/career_market_panel.csv</code></p>
<p>The corresponding variable documentation is stored as:</p>
<p><code>data/data_dictionary.csv</code></p>
</section>
<section id="step-2-limitations" class="level2" data-number="2.7">
<h2 data-number="2.7" class="anchored" data-anchor-id="step-2-limitations"><span class="header-section-number">2.7</span> Step 2 Limitations</h2>
<p>Several data-quality limitations should be considered when interpreting the results.</p>
<p>First, salary information is unavailable for 54 of the 140 postings.</p>
<p>Second, minimum experience is unavailable for 28 postings, while maximum experience is unavailable for most postings.</p>
<p>Third, 71 postings do not have a classified remote-work arrangement.</p>
<p>Finally, the dataset represents job postings rather than unique underlying job openings or hiring demand. Multiple postings may represent similar positions or repeated recruiting activity.</p>
<p>These limitations are documented rather than addressed through aggressive imputation so that the baseline remains transparent and reproducible.</p>
</section>
</section>
<section id="sec-market-baseline" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Market Baseline</h1>
<section id="market-baseline" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="market-baseline"><span class="header-section-number">3.1</span> Market Baseline</h2>
<p>This page provides an exploratory baseline of the career market for Data Analyst roles within <strong>NAICS 523 — Securities, Commodity Contracts, and Other Financial Investments and Related Activities</strong>.</p>
<p>The revised analysis uses the professor-approved Lightcast job-postings dataset and includes postings classified within the NAICS 523 subsector.</p>
</section>
<section id="industry-scope" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="industry-scope"><span class="header-section-number">3.2</span> Industry Scope</h2>
<p>The analysis is restricted to:</p>
<ul>
<li><strong>NAICS:</strong> 523</li>
<li><strong>Industry:</strong> Securities, Commodity Contracts, and Other Financial Investments and Related Activities</li>
<li><strong>Career pathway:</strong> Data Analyst / Data Analytics</li>
</ul>
<p>The revised dataset contains <strong>140 postings</strong> after applying the career-title filter and excluding clearly unrelated roles.</p>
</section>
<section id="job-volume-by-title" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="job-volume-by-title"><span class="header-section-number">3.3</span> Job Volume by Title</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/revised/job_volume_by_title.png" class="img-fluid figure-img"></p>
<figcaption>Job volume by title</figcaption>
</figure>
</div>
<p>The Data Analyst sample contains a range of analyst titles, including Product Data Analyst, Data Analyst, Data Analyst II, Senior Data Analyst, and other specialized analyst positions.</p>
<p>Product Data Analyst is the most frequent title in the revised sample.</p>
</section>
<section id="top-employers" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="top-employers"><span class="header-section-number">3.4</span> Top Employers</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/revised/top_employers.png" class="img-fluid figure-img"></p>
<figcaption>Top employers</figcaption>
</figure>
</div>
<p>The largest employer represented in the revised sample is <strong>Lincoln Financial Group</strong>, followed by <strong>The Vanguard Group</strong> and <strong>Fidelity Investments</strong>.</p>
<p>This concentration indicates that some employers contribute substantially more postings than others and should be considered when interpreting overall market demand.</p>
</section>
<section id="hiring-locations" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="hiring-locations"><span class="header-section-number">3.5</span> Hiring Locations</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/revised/top_locations.png" class="img-fluid figure-img"></p>
<figcaption>Top hiring locations</figcaption>
</figure>
</div>
<p>The revised sample is geographically distributed across multiple states.</p>
<p>The largest state concentrations are Massachusetts, North Carolina, Pennsylvania, Texas, and Arizona.</p>
</section>
<section id="remote-work-1" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="remote-work-1"><span class="header-section-number">3.6</span> Remote Work</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/revised/remote_status.png" class="img-fluid figure-img"></p>
<figcaption>Remote work status</figcaption>
</figure>
</div>
<p>The revised sample contains:</p>
<ul>
<li><strong>54 Remote</strong></li>
<li><strong>12 Hybrid Remote</strong></li>
<li><strong>3 Not Remote</strong></li>
<li><strong>71 Unknown</strong></li>
</ul>
<p>Because more than half of the postings have an unknown remote classification, the results should not be interpreted as a complete estimate of remote-work availability.</p>
</section>
<section id="salary-distribution" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="salary-distribution"><span class="header-section-number">3.7</span> Salary Distribution</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/revised/salary_distribution.png" class="img-fluid figure-img"></p>
<figcaption>Salary distribution</figcaption>
</figure>
</div>
<p>A usable salary midpoint could be calculated for <strong>86 of the 140 postings</strong>.</p>
<p>The annual salary midpoint distribution across the 86 posting rows has:</p>
<ul>
<li><strong>Mean:</strong> $90,860.55</li>
<li><strong>Median:</strong> $93,850</li>
<li><strong>Minimum:</strong> $24,960</li>
<li><strong>Maximum:</strong> $160,000</li>
</ul>
<p>Salary information was retained as missing when salary endpoints were unavailable rather than treating missing salary as zero. The <a href="./ml_methods.html">final analytics</a> also reports 48 distinct salary profiles, with a median of approximately <strong>$92,300</strong>. The two medians use different counting units: posting rows and distinct profiles.</p>
</section>
<section id="experience-requirements" class="level2" data-number="3.8">
<h2 data-number="3.8" class="anchored" data-anchor-id="experience-requirements"><span class="header-section-number">3.8</span> Experience Requirements</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/revised/experience_requirements.png" class="img-fluid figure-img"></p>
<figcaption>Experience requirements</figcaption>
</figure>
</div>
<p>Minimum experience information was available for <strong>112 postings</strong>.</p>
<p>Among postings with a reported minimum experience requirement:</p>
<ul>
<li><strong>Mean:</strong> 4.11 years</li>
<li><strong>Median:</strong> 5 years</li>
<li><strong>Minimum:</strong> 0 years</li>
<li><strong>Maximum:</strong> 12 years</li>
</ul>
<p>Maximum experience requirements were frequently missing, so the analysis focuses on the minimum experience field.</p>
</section>
<section id="data-quality-and-limitations" class="level2" data-number="3.9">
<h2 data-number="3.9" class="anchored" data-anchor-id="data-quality-and-limitations"><span class="header-section-number">3.9</span> Data Quality and Limitations</h2>
<p>The revised analysis provides a substantially larger career-specific sample than the original MET API analysis.</p>
<p>The original Step 2 analysis was limited to 400 retrieved NAICS 523000 records and identified only two direct Data Analyst matches. The revised analysis uses the Lightcast dataset approved for the project and the three-digit NAICS 523 subsector.</p>
<p>The career filter was intentionally expanded to capture relevant Data Analyst titles while excluding clearly unrelated categories such as maintenance, cybersecurity, academic roles, internships, and other specialized positions that did not fit the project’s intended career pathway.</p>
<p>Missing salary, experience, and remote-work information was retained and explicitly reported rather than being converted into misleading values.</p>
</section>
<section id="summary" class="level2" data-number="3.10">
<h2 data-number="3.10" class="anchored" data-anchor-id="summary"><span class="header-section-number">3.10</span> Summary</h2>
<p>The revised baseline provides a broader view of Data Analyst opportunities within financial services. The market includes multiple employers, geographic locations, salary ranges, experience requirements, and work arrangements.</p>
<p>These results provide the foundation for the next stage of the project: <strong>Step 3 skill-gap analysis and expanded EDA</strong>.</p>
</section>
</section>
<section id="sec-skill-gap" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Skill-Gap Analysis</h1>
<section id="skill-gap-analysis" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="skill-gap-analysis"><span class="header-section-number">4.1</span> Skill Gap Analysis</h2>
<p>This page compares the skills requested in Data Analyst job postings within NAICS 523 with the current self-assessed skill levels of the project team.</p>
<p>The analysis uses the revised 140-posting Data Analyst dataset developed in Step 2 and focuses on skills that can be meaningfully compared with the team’s current capabilities.</p>
</section>
<section id="team-skill-self-assessment" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="team-skill-self-assessment"><span class="header-section-number">4.2</span> Team Skill Self-Assessment</h2>
<p>Each team member rated current proficiency using a five-point scale:</p>
<ul>
<li><strong>1 — Beginner</strong></li>
<li><strong>2 — Basic Knowledge</strong></li>
<li><strong>3 — Intermediate</strong></li>
<li><strong>4 — Advanced</strong></li>
<li><strong>5 — Expert</strong></li>
</ul>
<p>The assessment covers technical, analytical, visualization, cloud, and business-analysis skills relevant to the Data Analyst career pathway.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/team_skill_heatmap.png" class="img-fluid figure-img"></p>
<figcaption>Team skill self-assessment</figcaption>
</figure>
</div>
<p>The team reports relatively strong capabilities in Excel, data visualization, statistics, and business analysis.</p>
<p>Average proficiency is lower in Python, SQL, machine learning, PySpark / Big Data, and AWS / Cloud.</p>
<p>The heatmap also shows variation across team members. Some members report stronger business and spreadsheet skills, while others report relatively stronger statistics, visualization, or data-cleaning capabilities.</p>
</section>
<section id="market-skill-demand" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="market-skill-demand"><span class="header-section-number">4.3</span> Market Skill Demand</h2>
<p>Skill demand was calculated from the 140 Data Analyst postings by identifying the percentage of job postings containing each skill.</p>
<p>The most frequently requested skills in the revised dataset include:</p>
<ul>
<li><strong>Data Analysis — 69.3%</strong></li>
<li><strong>Communication — 60.7%</strong></li>
<li><strong>Tableau — 55.7%</strong></li>
<li><strong>SQL — 50.0%</strong></li>
<li><strong>Python — 37.1%</strong></li>
<li><strong>Excel — 23.6%</strong></li>
<li><strong>Data Visualization — 19.3%</strong></li>
<li><strong>Statistics — 10.7%</strong></li>
<li><strong>Machine Learning — 9.3%</strong></li>
<li><strong>Amazon Web Services — 7.1%</strong></li>
</ul>
<p>These results indicate that employers value a combination of analytical, technical, visualization, and communication capabilities.</p>
<p>SQL, Tableau, and Python stand out as especially important technical skills for the target Data Analyst pathway.</p>
</section>
<section id="skill-priority-matrix" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="skill-priority-matrix"><span class="header-section-number">4.4</span> Skill Priority Matrix</h2>
<p>The following matrix compares market demand with the team’s average self-assessed proficiency.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/skill_priority_matrix.png" class="img-fluid figure-img"></p>
<figcaption>Skill priority matrix</figcaption>
</figure>
</div>
<p>The horizontal axis represents the percentage of job postings containing each skill.</p>
<p>The vertical axis represents the team’s average proficiency on the 1–5 self-assessment scale.</p>
<p>The dashed lines represent the median market demand and median team proficiency across the comparable skills.</p>
<p>Skills in the lower-right portion of the chart represent the most important development opportunities because they combine relatively high employer demand with relatively lower current proficiency.</p>
</section>
<section id="key-skill-gaps" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="key-skill-gaps"><span class="header-section-number">4.5</span> Key Skill Gaps</h2>
<p><strong>SQL</strong> is the clearest priority area.</p>
<p>SQL appears in <strong>50.0%</strong> of the Data Analyst postings, while the team’s average proficiency is approximately <strong>2.33 out of 5</strong>.</p>
<p>This suggests that stronger SQL capability could directly improve alignment with current market requirements.</p>
<p><strong>Python</strong> is another important development area.</p>
<p>Python appears in <strong>37.1%</strong> of postings, while the team reports an average proficiency of approximately <strong>2.33 out of 5</strong>.</p>
<p>Improving Python skills would strengthen the team’s ability to perform data cleaning, analysis, automation, and reproducible analytical workflows.</p>
<p><strong>Power BI / Tableau</strong> also remains important because Tableau appears in <strong>55.7%</strong> of the postings.</p>
<p>The team’s average proficiency in this area is approximately <strong>3.33 out of 5</strong>, indicating a moderate level of capability but continued room for development.</p>
</section>
<section id="team-strengths" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="team-strengths"><span class="header-section-number">4.6</span> Team Strengths</h2>
<p>The team reports relatively strong capability in several areas.</p>
<p><strong>Excel</strong> has an average proficiency above 4 out of 5 and remains relevant across many analytical workflows.</p>
<p><strong>Data Visualization</strong> is another team strength, with all three members reporting advanced proficiency.</p>
<p>The team also reports comparatively strong capabilities in <strong>statistics</strong> and <strong>business analysis</strong>.</p>
<p>These strengths can support the development of weaker technical areas by allowing team members to focus on translating analysis into clear business insights and visual communication.</p>
</section>
<section id="individual-development-priorities" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="individual-development-priorities"><span class="header-section-number">4.7</span> Individual Development Priorities</h2>
<p>Based on the combination of market demand and self-assessed proficiency, the highest-priority development areas are:</p>
<section id="taiqi" class="level3" data-number="4.7.1">
<h3 data-number="4.7.1" class="anchored" data-anchor-id="taiqi"><span class="header-section-number">4.7.1</span> Taiqi</h3>
<ul>
<li><strong>SQL — High Priority</strong></li>
<li><strong>Python — High Priority</strong></li>
<li><strong>Power BI / Tableau — Medium Priority</strong></li>
</ul>
<p>Taiqi should continue developing SQL and Python while building on existing strengths in Excel, visualization, and business analysis.</p>
</section>
<section id="joseph" class="level3" data-number="4.7.2">
<h3 data-number="4.7.2" class="anchored" data-anchor-id="joseph"><span class="header-section-number">4.7.2</span> Joseph</h3>
<ul>
<li><strong>SQL — High Priority</strong></li>
<li><strong>Python — High Priority</strong></li>
<li><strong>Power BI / Tableau — High Priority</strong></li>
</ul>
<p>Joseph’s strongest development opportunity is increasing practical experience with SQL, Python, and business-intelligence tools.</p>
</section>
<section id="igor" class="level3" data-number="4.7.3">
<h3 data-number="4.7.3" class="anchored" data-anchor-id="igor"><span class="header-section-number">4.7.3</span> Igor</h3>
<ul>
<li><strong>SQL — High Priority</strong></li>
<li><strong>Python — High Priority</strong></li>
<li><strong>Power BI / Tableau — High Priority</strong></li>
</ul>
<p>Igor reports strong Excel and business-analysis skills, while SQL and Python represent important opportunities to strengthen technical alignment with the job market.</p>
</section>
</section>
<section id="improvement-plan" class="level2" data-number="4.8">
<h2 data-number="4.8" class="anchored" data-anchor-id="improvement-plan"><span class="header-section-number">4.8</span> Improvement Plan</h2>
<p>The team should prioritize practical development in three areas:</p>
<ol type="1">
<li><strong>SQL</strong>
<ul>
<li>Practice joins, common table expressions, window functions, aggregation, and analytical queries.</li>
<li>Apply SQL to realistic business and job-market datasets.</li>
</ul></li>
<li><strong>Python</strong>
<ul>
<li>Strengthen pandas, data cleaning, exploratory analysis, visualization, and automation.</li>
<li>Continue using notebooks and project-based exercises.</li>
</ul></li>
<li><strong>Power BI / Tableau</strong>
<ul>
<li>Build interactive dashboards using filters, calculated fields, drill-downs, and clear business storytelling.</li>
<li>Practice translating analytical findings into decision-oriented visualizations.</li>
</ul></li>
</ol>
<p>Secondary development areas include machine learning, cloud platforms, and big-data tools.</p>
<p>These skills currently appear less frequently in the sample than SQL, Python, and Tableau, but they may become increasingly useful for more advanced analytics roles.</p>
</section>
<section id="team-collaboration" class="level2" data-number="4.9">
<h2 data-number="4.9" class="anchored" data-anchor-id="team-collaboration"><span class="header-section-number">4.9</span> Team Collaboration</h2>
<p>The team can reduce skill gaps by sharing technical resources and using project work as structured practice.</p>
<p>Possible approaches include:</p>
<ul>
<li>reviewing one another’s SQL queries and Python notebooks;</li>
<li>sharing visualization and dashboard techniques;</li>
<li>dividing analytical tasks based on individual strengths;</li>
<li>documenting useful coding patterns and resources in the shared repository;</li>
<li>using future project stages to practice weaker technical skills.</li>
</ul>
<p>Members with stronger Excel, visualization, statistics, and business-analysis skills can support the team in those areas while strengthening their own SQL, Python, and cloud capabilities.</p>
</section>
<section id="limitations" class="level2" data-number="4.10">
<h2 data-number="4.10" class="anchored" data-anchor-id="limitations"><span class="header-section-number">4.10</span> Limitations</h2>
<p>The skill comparison has several limitations.</p>
<p>Market demand is based on the percentage of job postings containing each skill, while team proficiency is based on self-assessment.</p>
<p>These measures are not directly equivalent and should not be interpreted as a statistical difference.</p>
<p>Instead, the comparison is used as a practical prioritization framework to identify skills that are both important in the job market and relatively underdeveloped within the team.</p>
<p>The analysis is also limited to the revised 140-posting Data Analyst sample within NAICS 523 and therefore does not represent the entire Data Analyst labor market.</p>
</section>
<section id="summary-1" class="level2" data-number="4.11">
<h2 data-number="4.11" class="anchored" data-anchor-id="summary-1"><span class="header-section-number">4.11</span> Summary</h2>
<p>The Step 3 skill-gap analysis identifies a clear distinction between current team strengths and market-driven development priorities.</p>
<p>The team is relatively strong in Excel, visualization, statistics, and business analysis.</p>
<p>However, <strong>SQL, Python, and business-intelligence tools represent the most important areas for continued development because they combine substantial market demand with lower or moderate current proficiency</strong>.</p>
<p>These findings provide a practical foundation for the team’s future learning priorities and later career recommendations.</p>
</section>
</section>
<section id="sec-final-analytics" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Final Analytics</h1>
<section id="purpose" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="purpose"><span class="header-section-number">5.1</span> Purpose</h2>
<p>Can experience, location, remote status and required skills help explain differences in advertised salaries?</p>
<p>We compare multiple linear regression and Random Forest with a simple average-salary baseline. The aim is to judge whether a model adds useful information to the salary benchmarks from the <a href="./market_baseline.html">market baseline</a>.</p>
</section>
<section id="data-used" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="data-used"><span class="header-section-number">5.2</span> Data Used</h2>
<ul>
<li><strong>140 Data Analyst postings</strong> in NAICS 523, posted between May and September 2024.</li>
<li><strong>86 postings with a valid salary midpoint</strong>, representing <strong>48 distinct posting profiles</strong>.</li>
<li><strong>54 postings without salary</strong> remain in the wider market and skill analysis, but cannot be used to evaluate salary predictions.</li>
<li>The target is <strong>salary_midpoint</strong>, the average of the lower and upper annualized salary endpoints. Hourly and monthly amounts were already converted during preparation and are used without another conversion.</li>
</ul>
<p>The predictors are minimum experience, remote status, city, state and eight skill indicators: SQL, Python, Excel, Power BI / Tableau, statistics, visualization, machine learning and AWS. Salary endpoints are excluded from the predictors because they define the target.</p>
</section>
<section id="how-the-models-were-checked" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="how-the-models-were-checked"><span class="header-section-number">5.3</span> How the Models Were Checked</h2>
<ul>
<li>Divide the data into <strong>five validation parts</strong>.</li>
<li>Train a fresh model on four parts and predict salaries for the remaining part; repeat until every posting has been checked once.</li>
<li>Keep copies of the same employer/title/description together, so the model is checked on jobs it has not already seen.</li>
<li>Give each posting profile equal total weight, preventing a job advertised in many cities from dominating the results.</li>
<li>Fill missing experience using training data only; keep unknown remote status as its own category.</li>
</ul>
</section>
<section id="main-results" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="main-results"><span class="header-section-number">5.4</span> Main Results</h2>
<p>The mean-salary baseline predicts the same training average for every validation job. It is a simple benchmark used to judge whether the two predictive models add value.</p>
<p>Lower RMSE and MAE mean smaller salary errors. Higher R² means the model explains more of the salary variation in held-out data; it is not an accuracy percentage.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Model</th>
<th style="text-align: right;">RMSE</th>
<th style="text-align: right;">MAE</th>
<th style="text-align: right;">R²</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Random Forest</td>
<td style="text-align: right;">$23,781</td>
<td style="text-align: right;">$18,313</td>
<td style="text-align: right;">0.126</td>
</tr>
<tr class="even">
<td>Multiple linear regression</td>
<td style="text-align: right;">$25,419</td>
<td style="text-align: right;">$21,622</td>
<td style="text-align: right;">0.002</td>
</tr>
<tr class="odd">
<td>Mean-salary baseline</td>
<td style="text-align: right;">$25,572</td>
<td style="text-align: right;">$18,982</td>
<td style="text-align: right;">−0.010</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/ml_model_comparison.png" class="img-fluid figure-img"></p>
<figcaption>Salary-model comparison using grouped validation</figcaption>
</figure>
</div>
<ul>
<li><strong>Random Forest performs best</strong>, reducing RMSE by about <strong>7%</strong> compared with the baseline.</li>
<li>Its average absolute error is still about <strong>$18,300</strong>. The model provides limited support for a precise individual salary estimate.</li>
<li>Linear regression performs close to the baseline, suggesting that a simple linear relationship captures little of the observed salary variation.</li>
</ul>
</section>
<section id="which-factor-contributed-most" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="which-factor-contributed-most"><span class="header-section-number">5.5</span> Which Factor Contributed Most?</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/ml_forest_importance.png" class="img-fluid figure-img"></p>
<figcaption>Factors contributing to Random Forest salary predictions</figcaption>
</figure>
</div>
<ul>
<li><strong>Minimum experience is the strongest predictive signal</strong> in the Random Forest comparison.</li>
<li>Skill, remote and location indicators contribute less consistently to salary prediction in this small sample.</li>
<li>These are associations between job requirements and compensation. They do not show that learning a particular skill causes a pay increase.</li>
</ul>
</section>
<section id="what-this-means-for-a-job-seeker" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="what-this-means-for-a-job-seeker"><span class="header-section-number">5.6</span> What This Means for a Job Seeker</h2>
<ul>
<li>Use advertised salary ranges and the sample benchmarks as reference points.</li>
<li>Compare roles with similar experience requirements before comparing compensation.</li>
<li>Prioritize skills using employer demand and your own skill gaps; a weak salary predictor can still be an important job requirement.</li>
<li>Treat model estimates as exploratory. The sample is small, historical and limited to salary-disclosing postings.</li>
</ul>
</section>
<section id="limitations-1" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="limitations-1"><span class="header-section-number">5.7</span> Limitations</h2>
<ul>
<li><strong>Small salary sample:</strong> 86 postings represent only 48 profiles, so results are uncertain.</li>
<li><strong>Uneven regional and employer coverage:</strong> the selected historical sample does not establish national salary expectations or reliable regional pay differences.</li>
<li><strong>Missing and imperfect data:</strong> salaries, experience and remote status are incomplete; annualized salary values can still contain source errors.</li>
<li><strong>Limited model usefulness:</strong> MAE is about $18,300 and R² is 0.126. There is no independent final test, and predictive associations do not establish causal pay effects.</li>
</ul>
<p>Use actual advertised ranges and comparable roles when making decisions. See <a href="./limitations.html">Limitations</a> for the full report section and product boundaries.</p>
<p>Continue to <a href="./final_recommendations.html">Career Recommendations</a> for the practical learning and job-search priorities.</p>
</section>
</section>
<section id="sec-recommendations" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Recommendations</h1>
<section id="where-to-focus" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="where-to-focus"><span class="header-section-number">6.1</span> Where to Focus</h2>
<p>For students and early-career applicants pursuing Data Analyst roles in securities, investments and related financial activities, the clearest priorities are:</p>
<ul>
<li><strong>Strengthen SQL, Python and business-intelligence skills.</strong></li>
<li><strong>Target roles that match your experience.</strong></li>
<li><strong>Use salary benchmarks to compare opportunities.</strong></li>
<li><strong>Confirm location and remote requirements in each posting.</strong></li>
</ul>
<p>These recommendations combine the <a href="./data_preparation.html">data preparation</a>, <a href="./market_baseline.html">market baseline</a>, <a href="./skill_gap_analysis.html">skill-gap analysis</a> and <a href="./ml_methods.html">salary analysis</a>. The evidence covers <strong>140 postings from May–September 2024</strong>, representing <strong>102 distinct employer/title/description profiles</strong>. It is a historical snapshot, not a list of current vacancies.</p>
</section>
<section id="build-the-skills-employers-request" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="build-the-skills-employers-request"><span class="header-section-number">6.2</span> 1. Build the Skills Employers Request</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/final_skill_demand.png" class="img-fluid figure-img"></p>
<figcaption>Skill demand across posting rows and distinct posting profiles</figcaption>
</figure>
</div>
<p>After counting repeated descriptions once, the leading skills among the eight technical groups examined are:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 40%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Skill</th>
<th style="text-align: right;">Share of distinct profiles</th>
<th>Practical evidence to build</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SQL</td>
<td style="text-align: right;">67.6%</td>
<td>Queries using joins, aggregation and window functions to answer business questions.</td>
</tr>
<tr class="even">
<td>Python</td>
<td style="text-align: right;">51.0%</td>
<td>A reproducible notebook that cleans data, analyzes patterns and explains the findings.</td>
</tr>
<tr class="odd">
<td>Power BI / Tableau</td>
<td style="text-align: right;">50.0%</td>
<td>A dashboard with useful filters, clear measures and a short business explanation.</td>
</tr>
</tbody>
</table>
<p>Percentages use <strong>102 distinct profiles</strong>. The BI group includes either Power BI or Tableau; the two bars in the chart show how repeated postings affect demand counts.</p>
<p>The original skill-gap analysis also found <strong>Data Analysis in 69.3%</strong> and <strong>Communication in 60.7%</strong> of the 140 postings. Show that you can explain what the numbers mean and recommend a practical action, alongside demonstrating the tools.</p>
<p>For Group 4, the self-assessment identifies strengths in <strong>Excel, visualization, statistics and business analysis</strong>, with lower average ratings in <strong>SQL and Python (2.33/5)</strong>. The development priorities remain:</p>
<ul>
<li><strong>Taiqi:</strong> SQL and Python first; continue improving BI skills.</li>
<li><strong>Joseph and Igor:</strong> SQL, Python and BI first.</li>
<li>Build on existing strengths to produce clear, business-focused work. These ratings are self-assessments, not verified proficiency scores.</li>
</ul>
</section>
<section id="target-roles-that-fit-your-experience" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="target-roles-that-fit-your-experience"><span class="header-section-number">6.3</span> 2. Target Roles That Fit Your Experience</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/revised/experience_requirements.png" class="img-fluid figure-img"></p>
<figcaption>Reported minimum experience requirements for 112 of the 140 postings</figcaption>
</figure>
</div>
<ul>
<li><strong>26 postings, representing 25 profiles, require 0–2 years</strong> of minimum experience. Start by reviewing these roles and relevant junior or associate titles.</li>
<li><strong>79 postings require 3–5 years</strong>. Read the responsibilities carefully before deciding whether your previous work meets the requirement.</li>
<li><strong>28 postings omit minimum experience</strong>. Check the description; missing information does not mean no experience is required.</li>
</ul>
<p>Match your application to the actual responsibilities and required skills, rather than relying on the title alone.</p>
</section>
<section id="use-salary-as-a-benchmark" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="use-salary-as-a-benchmark"><span class="header-section-number">6.4</span> 3. Use Salary as a Benchmark</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/ml_salary_distribution.png" class="img-fluid figure-img"></p>
<figcaption>Annual salary midpoints across postings and distinct posting profiles</figcaption>
</figure>
</div>
<ul>
<li>Salary is available for <strong>86 postings</strong>, representing <strong>48 distinct profiles</strong>.</li>
<li>The distinct-profile median annual midpoint is approximately <strong>$92,300</strong>.</li>
<li>The middle 50% of profile midpoints falls roughly between <strong>$72,000 and $100,000</strong>.</li>
<li>This describes roles with different experience levels; it is not an entry-level salary expectation or an individual offer range.</li>
</ul>
<p>Compare each employer’s advertised range with similar roles, experience requirements and location. The best salary model still has an average absolute error of about <strong>$18,300</strong>, so the descriptive benchmark is more useful than treating a predicted number as a precise offer expectation.</p>
</section>
<section id="search-across-employers-and-work-arrangements" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="search-across-employers-and-work-arrangements"><span class="header-section-number">6.5</span> 4. Search Across Employers and Work Arrangements</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/final_state_opportunities.png" class="img-fluid figure-img"></p>
<figcaption>States with the most distinct posting profiles in the sample</figcaption>
</figure>
</div>
<ul>
<li><strong>Massachusetts, North Carolina and Pennsylvania</strong> lead the sample by distinct profiles. Use them as starting points for employer research, alongside locations that fit your circumstances.</li>
<li><strong>Lincoln Financial Group, Vanguard and Fidelity Investments</strong> are prominent in the market baseline. Use these names to explore relevant roles, while also considering other employers.</li>
<li><strong>54 postings are classified as remote</strong>, but <strong>71 have an unknown arrangement</strong>. Verify attendance and location requirements directly in the posting.</li>
<li>A job advertised in several cities may be one opening. Compare descriptions and requirements before treating every listing as a separate opportunity.</li>
</ul>
<p>These patterns show where the historical sample advertised roles; they do not establish which employers are hiring today or which location offers the best cost-adjusted salary.</p>
</section>
<section id="a-practical-next-step" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="a-practical-next-step"><span class="header-section-number">6.6</span> A Practical Next Step</h2>
<p>Build <strong>one finance-related portfolio project</strong> that combines the three priority tools:</p>
<ol type="1">
<li>Use <strong>SQL</strong> to organize the data and calculate meaningful business measures.</li>
<li>Use <strong>Python</strong> to clean, analyze and visualize the results.</li>
<li>Use <strong>Power BI or Tableau</strong> to present a dashboard and explain the decisions it supports.</li>
<li>Add the project to your CV and tailor the application to the skills and experience in each target role.</li>
</ol>
<p>For the career-readiness prototype, put these decisions first: show skill matches, learning priorities, experience fit and salary benchmarks with sample sizes. The study supports practical preparation and a more focused search; it does not guarantee a job offer or a salary increase.</p>
</section>
<section id="limitations-of-these-recommendations" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="limitations-of-these-recommendations"><span class="header-section-number">6.7</span> Limitations of These Recommendations</h2>
<ul>
<li>The small 2024 sample and uneven regional coverage do not support firm conclusions about the full or current labor market.</li>
<li>Missing salary, experience and remote information can bias comparisons; repeated advertising can inflate apparent opportunity counts.</li>
<li>Team skill ratings are self-assessments, and the salary model remains too uncertain for precise personal predictions.</li>
<li>The prototype provides preparation and search guidance. It does not yet track live vacancies, verify readiness, or measure hiring outcomes.</li>
</ul>
<p>The full <a href="./limitations.html">Limitations</a> section explains these boundaries and the next improvements.</p>
</section>
</section>
<section id="sec-limitations" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Limitations</h1>
<section id="limits-of-the-evidence" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="limits-of-the-evidence"><span class="header-section-number">7.1</span> Limits of the Evidence</h2>
<ul>
<li><strong>Small, selected sample.</strong> The study uses 140 Data Analyst postings in NAICS 523, representing 102 employer/title/description profiles. Salary analysis uses only 86 postings and 48 profiles. These findings are exploratory and do not support firm conclusions for the full Data Analyst market.</li>
<li><strong>Uneven geographic coverage.</strong> The data includes several states, but locations and employers are not evenly represented. Regional patterns describe this sample; they do not establish national demand, the best relocation choice, or salary differences after cost of living.</li>
<li><strong>Historical and incomplete records.</strong> The postings cover May–September 2024. Salary is missing for 54 postings, minimum experience for 28, and remote classification for 71. Missing information may affect which roles appear in each analysis.</li>
<li><strong>Postings are not confirmed openings or offers.</strong> One job can be advertised in several locations. Exact-text grouping reduces repeated counts but may miss similar reposts. Salary endpoints were annualized during preparation, but source discrepancies can remain; the low Ariel Investments value needs review.</li>
<li><strong>Modest predictive performance.</strong> Random Forest performs slightly better than the mean-salary benchmark, with MAE about $18,300 and R² 0.126. The models were compared using the same cross-validation results, with no separate final test. Predictions are too uncertain to serve as precise individual salary estimates.</li>
<li><strong>Skills and pay are not causal measures.</strong> Skill mentions describe posting requirements. Team proficiency is self-assessed, and the eight technical groups do not cover every skill. Neither demand percentages nor model importance establish hiring probability or a pay increase from learning a skill.</li>
</ul>
</section>
<section id="product-boundaries-and-next-steps" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="product-boundaries-and-next-steps"><span class="header-section-number">7.2</span> Product Boundaries and Next Steps</h2>
<p>The prototype supports <strong>learning priorities, experience fit, employer research and salary benchmarks</strong>. It does not yet provide live vacancy tracking, verified readiness scores, personalized offer predictions, or evidence that its advice improves hiring outcomes.</p>
<p>To strengthen the product:</p>
<ol type="1">
<li>Collect more recent, independent postings across states and employers, and verify salary values.</li>
<li>Assess skills through practical tasks and gather feedback from students using the recommendations.</li>
<li>Evaluate models on new employers or a later time period before offering individual salary estimates.</li>
</ol>
</section>
</section>
<section id="references" class="level1 unnumbered">
<h1 class="unnumbered">References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-chern2018" class="csl-entry" role="listitem">
Chern, Alan, Qiaoling Liu, Josh Chao, Mahak Goindani, and Faizan Javed. 2018. <span>“Automatically Detecting Errors in Employer Industry Classification Using Job Postings.”</span> <em>Data Science and Engineering</em> 3: 221–31. <a href="https://doi.org/10.1007/s41019-018-0071-7">https://doi.org/10.1007/s41019-018-0071-7</a>.
</div>
<div id="ref-naics2022" class="csl-entry" role="listitem">
Executive Office of the President, Office of Management and Budget. 2022. <em>North American Industry Classification System: United States, 2022</em>. <a href="https://www.census.gov/naics/reference_files_tools/2022_NAICS_Manual.pdf">https://www.census.gov/naics/reference_files_tools/2022_NAICS_Manual.pdf</a>.
</div>
<div id="ref-goindani2017" class="csl-entry" role="listitem">
Goindani, Mahak, Qiaoling Liu, Josh Chao, and Valentin Jijkoun. 2017. <span>“Employer Industry Classification Using Job Postings.”</span> <em>2017 IEEE International Conference on Data Mining Workshops (ICDMW)</em>. <a href="https://doi.org/10.1109/ICDMW.2017.30">https://doi.org/10.1109/ICDMW.2017.30</a>.
</div>
<div id="ref-pedregosa2011" class="csl-entry" role="listitem">
Pedregosa, Fabian, Gaël Varoquaux, Alexandre Gramfort, et al. 2011. <span>“Scikit-Learn: Machine Learning in Python.”</span> <em>Journal of Machine Learning Research</em> 12 (85): 2825–30. <a href="https://www.jmlr.org/papers/v12/pedregosa11a.html">https://www.jmlr.org/papers/v12/pedregosa11a.html</a>.
</div>
<div id="ref-tsvetkova2024" class="csl-entry" role="listitem">
Tsvetkova, Alexandra, Elettra D’Amico, Alexander Lembcke, Polina Knutsson, and Wessel Vermeulen. 2024. <em>How Well Do Online Job Postings Match National Sources in Large English Speaking Countries? Benchmarking Lightcast Data Against Statistical Sources Across Regions, Sectors and Occupations</em>. OECD Local Economic and Employment Development (LEED) Papers 2024/01. OECD Publishing. <a href="https://doi.org/10.1787/c17cae09-en">https://doi.org/10.1787/c17cae09-en</a>.
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>